FROM openjdk:8-jdk-alpine
# ARG JAR_FILE=./target/*.jar
# COPY ${JAR_FILE} app.jar
# ADD ./target/basePJT-0.0.1-SNAPSHOT.jar app.jar
ADD ./target/auth-0.0.1-SNAPSHOT.jar app.jar
ENV JAVA_OPTS=""

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENTRYPOINT ["java","-jar","/app.jar"]
