version: "3"
services:
  mysql:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    #networks:
    #  - field-network
    ports:
      - "3306:3306"
    volumes:
      - '/volumes/mysql_home:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: illeum123@
      MYSQL_DATABASE: illeum
      MYSQL_USER: illeum
      MYSQL_PASSWORD: illeum123@
      TZ: Asia/Seoul

  jenkins:
    image: jenkins/jenkins
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - "9090:8080"
    volumes:
      - '/volumes/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - '$HOME:/home'
    container_name: 'jenkins'
    environment:
      TZ: Asia/Seoul

  redis1:
   image: redis
   command: redis-server --requirepass illeum123@ --port 6379
   container_name: redis
   hostname: redis
   volumes:
     - '/volumes/redis_home:/usr/local/etc/redis'
   environment:
      TZ: Asia/Seoul
   restart: always
   #networks:
   #        - field-network
   ports:
     - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    volumes:
      - /volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - /volumes/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "illeum"
      RABBITMQ_DEFAULT_PASS: "illeum123"

#networks:
#  default:
#    external:
#      name: field-network
